/**
 * ask.js  -  query cache and LLM filter utilities for db.ask().
 */

// ─── Hash ─────────────────────────────────────────────────────────────────────

/**
 * Deterministic djb2-style hash of a string.
 * @param {string} str
 * @returns {string} 8-char hex
 */
function _djb2(str) {
  let h = 5381;
  for (let i = 0; i < str.length; i++) {
    h = ((h << 5) + h + str.charCodeAt(i)) | 0;
  }
  return (h >>> 0).toString(16).padStart(8, "0");
}

// ─── QueryCache ───────────────────────────────────────────────────────────────

/**
 * QueryCache  -  maps hash(collection + schema + query) → filter object.
 *
 * Persisted in the _meta collection so it survives connect/disconnect cycles.
 * The cache avoids calling the LLM again for the same question on the same schema.
 *
 * @param {object} [opts]
 * @param {number} [opts.maxSize=500] - Maximum number of entries. Oldest entry is evicted when full.
 * @param {number} [opts.ttl=0]      - Entry TTL in ms. 0 = no expiry.
 */
class QueryCache {
  constructor({ maxSize = 500, ttl = 0 } = {}) {
    this._cache   = new Map();
    this._maxSize = maxSize;
    this._ttl     = ttl;
  }

  _key(collectionName, schema, query) {
    return _djb2(JSON.stringify({ collectionName, schema, query }));
  }

  get(collectionName, schema, query) {
    const key   = this._key(collectionName, schema, query);
    const entry = this._cache.get(key);
    if (!entry) return undefined;
    if (this._ttl > 0 && Date.now() - entry.ts > this._ttl) {
      this._cache.delete(key);
      return undefined;
    }
    return entry.filter;
  }

  set(collectionName, schema, query, filter) {
    const key = this._key(collectionName, schema, query);
    // Evict oldest entry when at capacity (and key is new)
    if (this._cache.size >= this._maxSize && !this._cache.has(key)) {
      this._cache.delete(this._cache.keys().next().value);
    }
    this._cache.set(key, { filter, ts: Date.now() });
  }

  toJSON() {
    return Object.fromEntries(
      [...this._cache.entries()].map(([k, v]) => [k, v])
    );
  }

  fromJSON(data) {
    if (!data || typeof data !== "object") return;
    for (const [k, v] of Object.entries(data)) {
      this._cache.set(k, v);
    }
  }

  get size() {
    return this._cache.size;
  }
}

// ─── Filter helpers ───────────────────────────────────────────────────────────

/**
 * Convert an LLM-generated filter into a form matchesFilter() can execute.
 * - $regex string values → RegExp objects
 * - ISO date strings in range operators → Date objects
 *
 * @param {object} filter
 * @param {object} [opts]
 * @param {number} [opts.regexMaxLength=500] - Maximum allowed $regex pattern length.
 * @returns {object}
 */
function processLLMFilter(filter, { regexMaxLength = 500 } = {}) {
  if (typeof filter !== "object" || filter === null) return filter;

  const result = {};
  for (const key of Object.keys(filter)) {
    const val = filter[key];
    if (val && typeof val === "object" && !Array.isArray(val)) {
      const processed = {};
      for (const op of Object.keys(val)) {
        if (op === "$regex" && typeof val.$regex === "string") {
          if (val.$regex.length > regexMaxLength)
            throw new Error(`$regex pattern too long (max ${regexMaxLength} characters)`);
          // Reject patterns with nested quantifiers that cause catastrophic backtracking.
          // e.g. (a+)+, (a|a)*, (x+){2,}
          if (/\([^)]*[+*][^)]*\)[+*{]/.test(val.$regex))
            throw new Error(`$regex pattern rejected: nested quantifiers risk ReDoS`);
          try {
            processed.$regex = new RegExp(val.$regex);
          } catch {
            throw new Error(`invalid $regex pattern: "${val.$regex}"`);
          }
        } else if (["$gt", "$gte", "$lt", "$lte"].includes(op) && _isDateString(val[op])) {
          processed[op] = new Date(val[op]);
        } else {
          processed[op] = val[op];
        }
      }
      result[key] = processed;
    } else {
      result[key] = val;
    }
  }
  return result;
}

function _isDateString(val) {
  if (typeof val !== "string") return false;
  return /\d{4}-\d{2}-\d{2}/.test(val) && !isNaN(Date.parse(val));
}

/**
 * Validate a filter generated by an LLM against a known schema.
 * Returns warning strings for unknown fields  -  does not throw.
 *
 * @param {object} filter
 * @param {object|null} schema  - Plain { field: type } schema object.
 * @returns {string[]}
 */
function validateLLMFilter(filter, schema) {
  const warnings = [];
  if (!schema || typeof filter !== "object" || filter === null) return warnings;

  for (const key of Object.keys(filter)) {
    if (key.startsWith("$")) continue;
    const baseField = key.split(".")[0];
    if (!(baseField in schema)) {
      warnings.push(`Unknown field referenced in generated filter: "${key}"`);
    }
  }

  return warnings;
}

export { QueryCache, processLLMFilter, validateLLMFilter };
