/**
 * ask.js — query cache and LLM filter utilities for db.ask().
 */

// ─── Hash ─────────────────────────────────────────────────────────────────────

/**
 * Deterministic djb2-style hash of a string.
 * @param {string} str
 * @returns {string} 8-char hex
 */
function _djb2(str) {
  let h = 5381;
  for (let i = 0; i < str.length; i++) {
    h = Math.imul((h << 5) + h, 1) + str.charCodeAt(i) | 0;
  }
  return (h >>> 0).toString(16).padStart(8, "0");
}

// ─── QueryCache ───────────────────────────────────────────────────────────────

/**
 * QueryCache — maps hash(collection + schema + query) → filter object.
 *
 * Persisted in the _meta collection so it survives connect/disconnect cycles.
 * The cache avoids calling the LLM again for the same question on the same schema.
 */
class QueryCache {
  constructor() {
    this._cache = new Map();
  }

  _key(collectionName, schema, query) {
    return _djb2(JSON.stringify({ collectionName, schema, query }));
  }

  get(collectionName, schema, query) {
    return this._cache.get(this._key(collectionName, schema, query));
  }

  set(collectionName, schema, query, filter) {
    this._cache.set(this._key(collectionName, schema, query), filter);
  }

  toJSON() {
    return Object.fromEntries(this._cache);
  }

  fromJSON(data) {
    if (!data || typeof data !== "object") return;
    for (const [k, v] of Object.entries(data)) {
      this._cache.set(k, v);
    }
  }

  get size() {
    return this._cache.size;
  }
}

// ─── Filter helpers ───────────────────────────────────────────────────────────

/**
 * Convert an LLM-generated filter into a form matchesFilter() can execute.
 * - $regex string values → RegExp objects
 * - ISO date strings in range operators → Date objects
 *
 * @param {object} filter
 * @returns {object}
 */
function processLLMFilter(filter) {
  if (typeof filter !== "object" || filter === null) return filter;

  const result = {};
  for (const key of Object.keys(filter)) {
    const val = filter[key];
    if (val && typeof val === "object" && !Array.isArray(val)) {
      const processed = {};
      for (const op of Object.keys(val)) {
        if (op === "$regex" && typeof val.$regex === "string") {
          processed.$regex = new RegExp(val.$regex);
        } else if (["$gt", "$gte", "$lt", "$lte"].includes(op) && _isDateString(val[op])) {
          processed[op] = new Date(val[op]);
        } else {
          processed[op] = val[op];
        }
      }
      result[key] = processed;
    } else {
      result[key] = val;
    }
  }
  return result;
}

function _isDateString(val) {
  if (typeof val !== "string") return false;
  return /\d{4}-\d{2}-\d{2}/.test(val) && !isNaN(Date.parse(val));
}

/**
 * Validate a filter generated by an LLM against a known schema.
 * Returns warning strings for unknown fields — does not throw.
 *
 * @param {object} filter
 * @param {object|null} schema  - Plain { field: type } schema object.
 * @returns {string[]}
 */
function validateLLMFilter(filter, schema) {
  const warnings = [];
  if (!schema || typeof filter !== "object" || filter === null) return warnings;

  for (const key of Object.keys(filter)) {
    if (key.startsWith("$")) continue;
    const baseField = key.split(".")[0];
    if (!(baseField in schema)) {
      warnings.push(`Unknown field referenced in generated filter: "${key}"`);
    }
  }

  return warnings;
}

module.exports = { QueryCache, processLLMFilter, validateLLMFilter };
